In [2]:
#General role for slilising
#List slicing  --->if we write the number, it means it is excluded, not mentioned so it is included
fam=['liz', 1.73,'emma', 1.68,'mom', 1.71,'dad', 1.89]
print(fam[:4])
print(fam[5:])


['liz', 1.73, 'emma', 1.68]
[1.71, 'dad', 1.89]


In [31]:
fam=['liz', 1.73,'emma', 1.68,'mom', 1.71,'dad', 1.89]
fam_ext = fam + ["me", 1.79]  ##add
print(fam_ext)
print(fam.index("mom"))
print(fam.count(1.73))

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'me', 1.79]
None
4
1


In [8]:
del fam[2]
fam

['liz', 1.73, 1.68, 'mom', 1.71, 'dad', 1.89]

In [11]:
x = ["a","b","c"]
y = x
y[1] = "z"
print(y)
print(x)

['a', 'z', 'c']
['a', 'z', 'c']


In [14]:
#if we donnot want to change
x = ["a","b","c"]
y = list(x)
y[1] = "z"
print(x)

#OR

x = ["a","b","c"]
y = x[:]
y[1] = "z"
print(x)

['a', 'b', 'c']
['a', 'b', 'c']


In [28]:
#FUNCTION
print(round(1.68, 1))  #to one number ofter decimal
print(round(1.68))      # to nrearnest num up
##
sister = "liz"
print(sister.capitalize()) #capitalize
print(sister.replace("z","sa"))
#print(sister.repalce("z","s")) ##no for string
# 'list' ,and string object has no attribute 'replace'

1.7
2
Liz
lisa


In [ ]:
                                        ###Importing Numpy methods

In [43]:
#wrong
import numpy
array([1, 2, 3])

NameError: name 'array' is not defined

In [44]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

In [45]:
numpy.array([1, 2, 3])

array([1, 2, 3])

In [46]:
from numpy import array
array([1, 2, 3])

array([1, 2, 3])

In [50]:
#example
import numpy as np
fam = ["liz", 1.73,"emma", 1.68,"mom", 1.71,"dad", 1.89]
ext = fam + ["me", 1.79]
print(str(len(fam_ext)) + " elements in famext")
np_fam = np.array(fam_ext) # Clearly using NumPy

10 elements in famext


In [4]:
#calculaton with Numpy
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
import numpy as np
np_height=np.array(height)
np_weight=np.array(weight)
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [5]:
# + in conventional list =union
# + in numply list additiom
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])
print(python_list+python_list)
print(numpy_array+numpy_array)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [9]:
print(bmi)
print(bmi>23)
print(bmi[bmi>23])

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]
[False False False  True False]
[24.7473475]


In [26]:
#2D
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])
print(np_2d.shape)
print(np_2d[0]) #print first row
print(np_2d[0][2])  #print first row third column
#OR
print(np_2d[0,2])  #print first row third column
#-----
print(np_2d[:, 1:3])  #all from 1:3
print(np_2d[1, :])  #second row only
print(np_2d[1])  #second row only

(2, 5)
[1.73 1.68 1.71 1.89 1.79]
1.71
1.71
[[ 1.68  1.71]
 [59.2  63.6 ]]
[65.4 59.2 63.6 88.4 68.7]
[65.4 59.2 63.6 88.4 68.7]


In [31]:
import pandas as np
READ=np.read_csv("baseball.csv")
READ

Name Team        Position  Height  Weight    Age PosCategory
0       Adam_Donachie  BAL         Catcher      74     180  22.99     Catcher
1           Paul_Bako  BAL         Catcher      74     215  34.69     Catcher
2     Ramon_Hernandez  BAL         Catcher      72     210  30.78     Catcher
3        Kevin_Millar  BAL   First_Baseman      72     210  35.43   Infielder
4         Chris_Gomez  BAL   First_Baseman      73     188  35.71   Infielder
...               ...  ...             ...     ...     ...    ...         ...
1010    Brad_Thompson  STL  Relief_Pitcher      73     190  25.08     Pitcher
1011    Tyler_Johnson  STL  Relief_Pitcher      74     180  25.73     Pitcher
1012   Chris_Narveson  STL  Relief_Pitcher      75     205  25.19     Pitcher
1013    Randy_Keisler  STL  Relief_Pitcher      75     190  31.01     Pitcher
1014      Josh_Kinney  STL  Relief_Pitcher      73     195  27.92     Pitcher

[1015 rows x 7 columns]

In [34]:
READ['Name']

0         Adam_Donachie
1             Paul_Bako
2       Ramon_Hernandez
3          Kevin_Millar
4           Chris_Gomez
             ...       
1010      Brad_Thompson
1011      Tyler_Johnson
1012     Chris_Narveson
1013      Randy_Keisler
1014        Josh_Kinney
Name: Name, Length: 1015, dtype: object

In [8]:
import pandas as np
READ=np.read_csv("baseball.csv")
import numpy as np
print(np.mean(READ['Weight']))
print(np.median(READ['Weight']))
print(np.std(READ['Height']))

201.34876847290641
200.0
2.3127918810465395


In [11]:
height = np.round(np.random.normal(1, 5, 5000), 2)
weight = np.round(np.random.normal(2, 10, 5000), 2)
np_city = np.column_stack((height, weight))
np_city

array([[ -3.77,   3.13],
       [  2.52,   0.53],
       [ -4.27, -14.93],
       ...,
       [  4.53,   0.84],
       [  2.91, -21.14],
       [ -1.54,  19.8 ]])